[book]
authors = ["hinto.janai"]
language = "en"
multilingual = false
src = "src"
title = "Cuprate Architecture"
git-repository-url = "https://github.com/hinto-janai/cuprate-architecture"

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/hinto-janai/cuprate-architecture"
additional-css = ["last-changed.css"]